CREATE TABLE IF NOT EXISTS "user_account" (
	"user_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"full_name" VARCHAR(255),
	"email" VARCHAR(255),
	"password" VARCHAR(255),
	"join_date" TIMESTAMPTZ,
	"role" VARCHAR(255),
	PRIMARY KEY("user_id")
);

CREATE TABLE IF NOT EXISTS "portfolio" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER,
	"type" VARCHAR(255),
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "order" (
	"order_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"instr_id" INTEGER,
	"place_date" TIMESTAMPTZ,
	"type" VARCHAR(255),
	"status" VARCHAR(255),
	"user_id" INTEGER,
	"holding_id" INTEGER,
	"quote" DECIMAL,
	"actual_price" DECIMAL,
	PRIMARY KEY("order_id")
);

CREATE TABLE IF NOT EXISTS "instrument" (
	"instrument_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"symbol" VARCHAR(255),
	"full_name" VARCHAR(255),
	PRIMARY KEY("instrument_id")
);

CREATE TABLE IF NOT EXISTS "Holding" (
	"holding_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"order_date" TIMESTAMPTZ,
	"portfolio_id" INTEGER,
	"quote" DECIMAL,
	"quantity" DECIMAL,
	PRIMARY KEY("holding_id")
);

ALTER TABLE "portfolio"
ADD FOREIGN KEY("user_id") REFERENCES "user_account"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Holding"
ADD FOREIGN KEY("holding_id") REFERENCES "portfolio"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "order"
ADD FOREIGN KEY("holding_id") REFERENCES "Holding"("holding_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "order"
ADD FOREIGN KEY("user_id") REFERENCES "user_account"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;