spring.application.name=trading-platform-backend
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration,org.springframework.boot.jpa.autoconfigure.HibernateJpaAutoConfiguration
server.port=8081