CREATE TABLE IF NOT EXISTS "users" (
	"user_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"full_name" VARCHAR(255),
	"email" VARCHAR(255),
	"password" VARCHAR(255),
	"join_date" TIMESTAMPTZ,
	"role" VARCHAR(255),
	PRIMARY KEY("user_id")
);

CREATE TABLE IF NOT EXISTS "portfolio" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER,
	"type" VARCHAR(255),
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "instrument" (
	"instrument_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"symbol" VARCHAR(255),
	"full_name" VARCHAR(255),
	PRIMARY KEY("instrument_id")
);

CREATE TABLE IF NOT EXISTS "holding" (
	"holding_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"order_date" TIMESTAMPTZ,
	"portfolio_id" INTEGER,
	"quote" DECIMAL,
	"quantity" DECIMAL,
	PRIMARY KEY("holding_id")
);

CREATE TABLE IF NOT EXISTS "orders" (
	"order_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"instr_id" INTEGER,
	"place_date" TIMESTAMPTZ,
	"type" VARCHAR(255),
	"status" VARCHAR(255),
	"user_id" INTEGER,
	"holding_id" INTEGER,
	"quote" DECIMAL,
	"actual_price" DECIMAL,
	"quantity" DECIMAL,
	PRIMARY KEY("order_id")
);

ALTER TABLE "portfolio"
	ADD FOREIGN KEY("user_id") REFERENCES "users"("user_id")
	ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "holding"
	ADD FOREIGN KEY("portfolio_id") REFERENCES "portfolio"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "orders"
	ADD FOREIGN KEY("holding_id") REFERENCES "holding"("holding_id")
	ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "orders"
	ADD FOREIGN KEY("user_id") REFERENCES "users"("user_id")
	ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "orders"
	ADD FOREIGN KEY("instr_id") REFERENCES "instrument"("instrument_id")
	ON UPDATE NO ACTION ON DELETE NO ACTION;
