-- CREATE TABLE IF NOT EXISTS "user_account" (
-- 	"user_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
-- 	"full_name" VARCHAR(255) NOT NULL,
-- 	"email" VARCHAR(255) NOT NULL UNIQUE,
-- 	"password" VARCHAR(255) NOT NULL,
-- 	"join_date" TIMESTAMPTZ NOT NULL DEFAULT now(),
-- 	"role" VARCHAR(50) NOT NULL DEFAULT 'USER' CHECK ("role" IN ('USER', 'ADMIN')),
-- 	PRIMARY KEY("user_id")
-- );

-- CREATE TABLE IF NOT EXISTS "portfolio" (
-- 	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
-- 	"user_id" INTEGER NOT NULL,
-- 	"type" VARCHAR(255) NOT NULL,
-- 	PRIMARY KEY("id")
-- );

-- CREATE TABLE IF NOT EXISTS "instrument" (
-- 	"instrument_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
-- 	"symbol" VARCHAR(20) NOT NULL UNIQUE,
-- 	"full_name" VARCHAR(255) NOT NULL,
-- 	PRIMARY KEY("instrument_id")
-- );

-- CREATE TABLE IF NOT EXISTS "holding" (
-- 	"holding_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
-- 	"order_date" TIMESTAMPTZ NOT NULL DEFAULT now(),
-- 	"portfolio_id" INTEGER NOT NULL,
-- 	"quote" DECIMAL(19, 6) NOT NULL,
-- 	"quantity" DECIMAL(19, 6) NOT NULL,
-- 	PRIMARY KEY("holding_id")
-- );

-- CREATE TABLE IF NOT EXISTS "orders" (
-- 	"order_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
-- 	"instr_id" INTEGER NOT NULL,
-- 	"place_date" TIMESTAMPTZ NOT NULL DEFAULT now(),
-- 	"type" VARCHAR(255) NOT NULL,
-- 	"status" VARCHAR(255) NOT NULL DEFAULT 'PENDING',
-- 	"user_id" INTEGER NOT NULL,
-- 	"holding_id" INTEGER,
-- 	"quote" DECIMAL(19, 6) NOT NULL,
-- 	"actual_price" DECIMAL(19, 6),
-- 	"quantity" DECIMAL(19, 6) NOT NULL,
-- 	PRIMARY KEY("order_id")
-- );

-- ALTER TABLE "portfolio"
-- 	ADD FOREIGN KEY("user_id") REFERENCES "user_account"("user_id")
-- 	ON UPDATE NO ACTION ON DELETE NO ACTION;

-- ALTER TABLE "holding"
-- 	ADD FOREIGN KEY("portfolio_id") REFERENCES "portfolio"("id")
-- 	ON UPDATE NO ACTION ON DELETE NO ACTION;

-- ALTER TABLE "orders"
-- 	ADD FOREIGN KEY("holding_id") REFERENCES "holding"("holding_id")
-- 	ON UPDATE NO ACTION ON DELETE NO ACTION;

-- ALTER TABLE "orders"
-- 	ADD FOREIGN KEY("user_id") REFERENCES "user_account"("user_id")
-- 	ON UPDATE NO ACTION ON DELETE NO ACTION;

-- ALTER TABLE "orders"
-- 	ADD FOREIGN KEY("instr_id") REFERENCES "instrument"("instrument_id")
-- 	ON UPDATE NO ACTION ON DELETE NO ACTION;

-- CREATE INDEX ON "portfolio" ("user_id");
-- CREATE INDEX ON "holding" ("portfolio_id");
-- CREATE INDEX ON "orders" ("user_id");
-- CREATE INDEX ON "orders" ("instr_id");
-- CREATE INDEX ON "orders" ("holding_id");

-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.user_account (
  user_id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  full_name text,
  email text,
  password_hash text,
  join_date timestamp with time zone,
  role text,
  CONSTRAINT user_account_pkey PRIMARY KEY (user_id)
);
CREATE TABLE public.portfolio (
  portfolio_id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id integer,
  type text,
  CONSTRAINT portfolio_pkey PRIMARY KEY (portfolio_id),
  CONSTRAINT portfolio_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_account(user_id)
);
CREATE TABLE public.order (
  order_id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  instr_id integer,
  side text,
  portfolio_id integer,
  user_id integer,
  holding_id integer,
  quote numeric,
  final_price numeric,
  increase_threshold numeric,
  CONSTRAINT order_pkey PRIMARY KEY (order_id),
  CONSTRAINT order_holding_id_fkey FOREIGN KEY (holding_id) REFERENCES public.holding(holding_id),
  CONSTRAINT order_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_account(user_id),
  CONSTRAINT order_instr_id_fkey FOREIGN KEY (instr_id) REFERENCES public.instrument(instrument_id),
  CONSTRAINT order_portfolio_id_fkey FOREIGN KEY (portfolio_id) REFERENCES public.portfolio(portfolio_id)
);
CREATE TABLE public.instrument (
  instrument_id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  symbol text,
  full_name text,
  instrument_type text,
  CONSTRAINT instrument_pkey PRIMARY KEY (instrument_id)
);
CREATE TABLE public.holding (
  holding_id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  order_date timestamp with time zone,
  portfolio_id integer,
  purchased_price numeric,
  quantity numeric,
  CONSTRAINT holding_pkey PRIMARY KEY (holding_id),
  CONSTRAINT Holding_holding_id_fkey FOREIGN KEY (holding_id) REFERENCES public.portfolio(portfolio_id)
);
CREATE TABLE public.flyway_schema_history (
  installed_rank integer NOT NULL,
  version character varying,
  description character varying NOT NULL,
  type character varying NOT NULL,
  script character varying NOT NULL,
  checksum integer,
  installed_by character varying NOT NULL,
  installed_on timestamp without time zone NOT NULL DEFAULT now(),
  execution_time integer NOT NULL,
  success boolean NOT NULL,
  CONSTRAINT flyway_schema_history_pkey PRIMARY KEY (installed_rank)
);
CREATE TABLE public.order_status_change (
  order_status_change_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  order_id integer,
  status text,
  message text,
  change_date timestamp with time zone,
  CONSTRAINT order_status_change_pkey PRIMARY KEY (order_status_change_id),
  CONSTRAINT OrderStatusChange_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.order(order_id)
);
